[package]
name = "discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
socket2 = "0.6.1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }

